import { LineGroup, PhoneNumber, Agent, GlobalConfig, Operator } from './types';

export const OPERATORS = ['中国移动', '中国联通', '中国电信'];
export const CITIES = ['韶关', '茂名', '惠州', '广州', '深圳', '成都', '北京', '上海'];
export const PROVINCES = ['广东', '江苏', '浙江', '四川', '山东', '北京', '上海'];
export const BUSINESS_TYPES = ['催收业务', '营销推广', '客户回访', '行政通知'];

export const INITIAL_OPERATORS: Operator[] = [
  { id: '1', name: '中国移动', remark: '移动全国业务' },
  { id: '2', name: '中国联通', remark: '联通全国业务' },
  { id: '3', name: '中国电信', remark: '电信全国业务' },
];

export const INITIAL_LINE_GROUPS: LineGroup[] = [
  {
    id: '1',
    province: '广东',
    city: '韶关',
    operator: '中国移动',
    areaCode: '0751',
    totalConcurrency: 120,
    availableConcurrency: 120,
    maxCPS: 30,
    currentCPS: 0,
    onlineCount: 0,
    currentOnlineCount: 0,
    status: 'enabled',
    remark: '韶关测试线路',
  },
  {
    id: '2',
    province: '广东',
    city: '茂名',
    operator: '中国联通',
    areaCode: '0668',
    totalConcurrency: 24,
    availableConcurrency: 24,
    maxCPS: 30,
    currentCPS: 0,
    onlineCount: 0,
    currentOnlineCount: 0,
    status: 'enabled',
    remark: '茂名联通线路',
  },
  {
    id: '3',
    province: '广东',
    city: '惠州',
    operator: '中国电信',
    areaCode: '0752',
    totalConcurrency: 1000,
    availableConcurrency: 1000,
    maxCPS: 30,
    currentCPS: 0,
    onlineCount: 0,
    currentOnlineCount: 0,
    status: 'enabled',
    remark: '惠州核心线路',
  },
];

export const INITIAL_NUMBERS: PhoneNumber[] = [
  ...Array.from({ length: 20 }).map((_, i) => ({
    id: `idle-${i}`,
    number: Math.floor(80000000 + Math.random() * 9999999).toString(),
    operator: i < 7 ? '中国移动' : i < 14 ? '中国联通' : '中国电信',
    lineGroupId: (i % 3 + 1).toString(),
    businessType: '催收业务',
    dailyCalls: 0,
    totalCalls: 0,
    displayStatus: 'active' as any,
    status: 'normal' as any,
    remark: '测试空闲号',
  })),
  {
    id: '1',
    number: '88880001',
    lineGroupId: '1',
    operator: '中国移动',
    dailyCalls: 45,
    totalCalls: 450,
    displayStatus: 'active',
    status: 'normal',
    agentId: '1',
    businessType: '营销推广',
    createdAt: '2026-03-01 10:00:00',
    remark: '主推号',
  },
  {
    id: '2',
    number: '88880002',
    lineGroupId: '1',
    operator: '中国移动',
    dailyCalls: 12,
    totalCalls: 210,
    displayStatus: 'active' as any,
    status: 'cooling' as any,
    agentId: '1',
    businessType: '催收业务',
    coolingReason: '过去 1 小时内，累计拒接超过 10 次',
    createdAt: '2026-03-05 14:30:00',
    remark: '冷却中',
    coolingStartTime: '2026-03-31T06:00:00Z',
  },
  {
    id: '3',
    number: '66661111',
    lineGroupId: '1',
    operator: '中国电信',
    dailyCalls: 0,
    totalCalls: 1200,
    displayStatus: 'inactive' as any,
    status: 'suspended_with_agent' as any,
    agentId: '2',
    businessType: '客户回访',
    createdAt: '2026-03-10 09:00:00',
    remark: '随坐席挂起中',
  },
  {
    id: '4',
    number: '22223333',
    lineGroupId: '1',
    operator: '中国联通',
    dailyCalls: 5,
    totalCalls: 890,
    displayStatus: 'inactive' as any,
    status: 'disabled' as any,
    businessType: '行政通知',
    createdAt: '2026-03-15 16:20:00',
    remark: '高频标记已停用',
  },
];

export const INITIAL_AGENTS: Agent[] = [
  {
    id: '1',
    name: '上海坐席-01',
    operator: '中国移动',
    lineGroupId: '1',
    numberCount: 2,
    availableNumberCount: 2,
    concurrencyLimit: 50,
    associatedAccounts: ['user_001'],
    associatedScripts: ['核心催收脚本'],
    status: 'enabled',
    remark: '主要负责上海业务',
  },
];

export const INITIAL_CONFIG: GlobalConfig = {
  coolingRule: {
    rejectionLimit: 10,
    rejectionWindow: 1,
    shortCallDuration: 3,
    shortCallCountLimit: 5,
    shortCallWindow: 1,
    coolingHours: 2,
  },
  concurrencyRule: {
    defaultCPS: 30,
    maxGlobalVoiceCloneConcurrency: 10,
  },
  forbiddenHours: {
    start: '22:00',
    end: '08:00',
  },
  autoReplenishCooling: true,
  autoReplenishDisabled: true,
  replenishLimit24h: 50,
};
